[target.aarch64-linux-android]
linker = "clang"

[target.armv7-linux-androideabi]
linker = "clang"
rustflags = ["-C", "link-arg=--target=armv7-linux-androideabi"]

[target.i686-linux-android]
linker = "clang"
rustflags = ["-C", "link-arg=--target=i686-linux-android"]

[target.x86_64-linux-android]
linker = "clang"
rustflags = ["-C", "link-arg=--target=x86_64-linux-android"]
